export const defaultSiteCopy = {
  navWork: 'Work',
  navAbout: 'About',
  navCareer: 'Career',
  navSkills: 'Skills',
  navContact: 'Contact',
  navAvailability: 'Available',
  heroScroll: 'Scroll',
  aboutLabel: '01 — ABOUT',
  aboutBasedIn: 'Based in',
  aboutSpecialization: 'Specialization',
  aboutExperience: 'Experience',
  aboutAvailability: 'Availability',
  careerLabel: '02 — CAREER',
  careerTitle: 'Experience',
  educationLabel: '03 — EDUCATION',
  educationTitle: 'Where the foundation was built.',
  workLabel: '04 — SELECTED WORK',
  workTitle: 'Work worth watching.',
  workAll: 'All',
  servicesLabel: '05 — SERVICES',
  servicesTitle: 'What I do',
  skillsLabel: '06 — SKILLS',
  skillsTitle: 'Tools of the trade.',
  processLabel: '07 — PROCESS',
  processTitle: 'From raw footage to final frame.',
  contactLabel: "08 — LET'S WORK",
  contactTitle: 'Have a story worth telling?',
  contactIntro: "Let's turn your footage, ideas or next project into something people want to watch.",
  contactName: 'Name',
  contactEmail: 'Email',
  contactProjectType: 'Project type',
  contactMessage: 'Message',
  contactNamePlaceholder: 'Your name',
  contactEmailPlaceholder: 'you@email.com',
  contactProjectTypePlaceholder: 'Select a project type',
  contactOtherType: 'Other',
  contactMessagePlaceholder: 'Tell me about your project...',
  contactButton: 'Start a conversation',
  contactSentTitle: 'Message sent.',
  contactSentBody: "Thanks for reaching out — I'll be in touch shortly.",
  contactSendError: 'Failed to send message. Please try again.',
  contactDirect: 'Direct',
  contactSocial: 'Social',
  contactEmailUnavailable: 'Email coming soon',
  footerNavigation: 'Navigation',
  footerConnect: 'Connect',
  projectClose: 'Close',
  projectCategory: 'Category',
  projectYear: 'Year',
  projectClient: 'Client',
  projectRole: 'Role',
  projectAbout: 'About the project',
  projectMyRole: 'My role',
  projectTools: 'Tools',
  projectVideoComingSoon: 'Video coming soon',
  projectNextLabel: 'Next project',
  projectNextAction: 'View next work',
} as const;

export type SiteCopy = { [K in keyof typeof defaultSiteCopy]: string };

export const siteCopyGroups: { title: string; fields: { key: keyof SiteCopy; label: string }[] }[] = [
  { title: 'Navigation', fields: [
    { key: 'navWork', label: 'Work link' }, { key: 'navAbout', label: 'About link' },
    { key: 'navCareer', label: 'Career link' }, { key: 'navSkills', label: 'Skills link' },
    { key: 'navContact', label: 'Contact link' }, { key: 'navAvailability', label: 'Availability badge' },
  ] },
  { title: 'Hero and About', fields: [
    { key: 'heroScroll', label: 'Scroll hint' }, { key: 'aboutLabel', label: 'About label' },
    { key: 'aboutBasedIn', label: 'Based in label' }, { key: 'aboutSpecialization', label: 'Specialization label' },
    { key: 'aboutExperience', label: 'Experience label' }, { key: 'aboutAvailability', label: 'Availability label' },
  ] },
  { title: 'Section headings', fields: [
    { key: 'careerLabel', label: 'Career label' }, { key: 'careerTitle', label: 'Career heading' },
    { key: 'educationLabel', label: 'Education label' }, { key: 'educationTitle', label: 'Education heading' },
    { key: 'workLabel', label: 'Work label' }, { key: 'workTitle', label: 'Work heading' },
    { key: 'workAll', label: 'All projects filter' },
    { key: 'servicesLabel', label: 'Services label' }, { key: 'servicesTitle', label: 'Services heading' },
    { key: 'skillsLabel', label: 'Skills label' }, { key: 'skillsTitle', label: 'Skills heading' },
    { key: 'processLabel', label: 'Process label' }, { key: 'processTitle', label: 'Process heading' },
  ] },
  { title: 'Contact form', fields: [
    { key: 'contactLabel', label: 'Contact label' }, { key: 'contactTitle', label: 'Contact heading' },
    { key: 'contactIntro', label: 'Introduction' }, { key: 'contactName', label: 'Name label' },
    { key: 'contactEmail', label: 'Email label' }, { key: 'contactProjectType', label: 'Project type label' },
    { key: 'contactMessage', label: 'Message label' }, { key: 'contactNamePlaceholder', label: 'Name placeholder' },
    { key: 'contactEmailPlaceholder', label: 'Email placeholder' },
    { key: 'contactProjectTypePlaceholder', label: 'Project type placeholder' },
    { key: 'contactOtherType', label: 'Other project type' },
    { key: 'contactMessagePlaceholder', label: 'Message placeholder' }, { key: 'contactButton', label: 'Submit button' },
    { key: 'contactSentTitle', label: 'Success heading' }, { key: 'contactSentBody', label: 'Success message' },
    { key: 'contactSendError', label: 'Send error message' },
    { key: 'contactDirect', label: 'Direct label' }, { key: 'contactSocial', label: 'Social label' },
    { key: 'contactEmailUnavailable', label: 'Missing email message' },
  ] },
  { title: 'Footer and project details', fields: [
    { key: 'footerNavigation', label: 'Footer navigation' }, { key: 'footerConnect', label: 'Footer connect' },
    { key: 'projectClose', label: 'Close button' }, { key: 'projectCategory', label: 'Category label' },
    { key: 'projectYear', label: 'Year label' }, { key: 'projectClient', label: 'Client label' },
    { key: 'projectRole', label: 'Role label' }, { key: 'projectAbout', label: 'About project heading' },
    { key: 'projectMyRole', label: 'My role heading' }, { key: 'projectTools', label: 'Tools heading' },
    { key: 'projectVideoComingSoon', label: 'Missing video message' },
    { key: 'projectNextLabel', label: 'Next project label' },
    { key: 'projectNextAction', label: 'Next project button' },
  ] },
];
